# Generated by Django 4.0.2 on 2022-02-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barber_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
                ('Image', models.ImageField(default='', upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='service_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=32)),
                ('password', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='booking_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=32)),
                ('date', models.CharField(default='', max_length=32)),
                ('status', models.CharField(default='Pending', max_length=32)),
                ('barbername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberapp.barber_register')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberapp.user_register')),
            ],
        ),
        migrations.AddField(
            model_name='barber_register',
            name='servicename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberapp.service_register'),
        ),
    ]
